### ISSUE TITLE
Request for download button/icon with Social buttons

### ISSUE THREAD

**Issue by rgvxsthi** [sproogen/modern-resume-theme#102]
**Is your feature request related to a problem? Please describe.**
A download button linking to a file (useful for linking externally to a CV/Resume would be pretty handy and useful.

**Describe the solution you'd like**
Maybe have another link similar to website/repo link?

**Describe alternatives you've considered**
Have tried using the "Additional Links" way of adding an icon but seems that it only works for Brands-based Social Media icons (or maybe I'm doing something wrong?)

**Additional context**
Code: https://i.imgur.com/l1IlESb.png
Icon showing up on the site: https://i.imgur.com/Q0ssVkc.png
The icon that I've tried: https://fontawesome.com/icons/download?style=solid

**Comment by rpzigler** [comment]
The download link doesn't work because the icon's prefix is different than the brand icons prefix. In order to use that icon, you do use `<i class="fas fa-download">`but the template is hardcoded (on line 103 of _includes/header.html) to use `<i class="fab {{ link.icon }}"` where {{ link.icon }} is a variable that is replaced by the icon name you entered in config.yml. 

So when you enter `fa-download` in config.yml, the resulting HTML as rendered by your browser is looking for the Font Awesome icon `fab fa-download` instead of `fas fa-download`. Since `fab fa-download` doesn't exist, you end up with `~` being displayed, which is basically saying Font Awesome's way of saying the icon link is broken/incorrect.

Because Font Awesome has multiple prefixes like fas, fab, far, fal, etc. it would be theoretically possible to change the config.yml to something like:

```
additional_links:
- title: 'Download Resume'
  fa_prefix: 'fas'
  icon: 'fa-download'
  url: 'rgvxsthi.github.io'
```
and the _includes/header.html to:
`<i class="{{ fa_prefix }} {{ link.icon }}"`

but it would just be easier to change the hardcoded Font Awesome prefix. So update line 103 in _includes/header.html to be:

`<i class="fas {{ link.icon }}" title="{{ link.title | escape }}"></i>`

**Comment by sproogen** [comment]
Hi, in my latest PR (#117) I have removed the hardcoding for the 'fab' part of the icons, so you should be able to now specify prefix in the icon name to use the other types of icons. I will try and get this merged shortly. This should fix this issue.
