### ISSUE TITLE
Skills section 

### ISSUE THREAD

**Issue by bertrand-benoit** [sproogen/modern-resume-theme#78]
Hey,

Do you plan implementing a Skills section (for instance with progress bars) ?
Do you have any base for this ?

**Comment by sproogen** [comment]
Hi,

Yes this is something I have been thinking about. First I want to update how data is defined, like experience and education, so that these aren't individually defined in the template and instead as config defined categories that can be configured in the config.yml without needing to update the html.

I think that will then allow me to add different types of categories such as skills that will work for everyone.

I can't say when I will get around to this yet, but it's going to be a fairly big change and I need to keep it backwards compatible too.

I will add updates here as they happen, but if you have any UX mocks of how you might like it to look then please share them.

Thanks

**Comment by gabrielcalderon** [comment]
@sproogen Any updates on this feature? :-)

**Comment by karmanyaahm** [comment]
Perhaps you could make it v2.0 which could relieve having to ensure backward compatibility. It is still a big change but one that would make this theme even more awesome.

**Comment by filipef101** [comment]
Cool, can't wait for it !

**Comment by bertrand-benoit** [comment]
@sproogen Any news?

**Comment by filipef101** [comment]
I modified to have something like that. You can check at filas.me and the code at my github pages repo

**Comment by sproogen** [comment]
Sorry it's taken so long to get around to it, but I finally decided on how I wanted this to work and now have a PR(#117) up with a config version v2. This will allow you to create/remove/order your content sections without changing the code. I'm hoping to get this merged shortly and then work on some different content sections layouts for things like skills.
