### ISSUE TITLE
Dark mode persists with or without the configuration set in `config.yml`

### ISSUE THREAD

**Issue by kurtlocker** [sproogen/modern-resume-theme#97]
**Describe the bug**
Dark mode persists without any dark-specific config.

**To Reproduce**
1. Do not add `darkmode: true` to the `_config.yml`. 
2. Run the application locally.

OR

1. Add `darkmode: false` to `_config.yml`
2. Run the application locally.

**Expected behavior**
Light mode

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser All
 - Version Most recent

**Additional Context**
Please see [my project setup](https://github.com/kurtlocker/resume/tree/gh-pages).

**Comment by sproogen** [comment]
I think what is happening here is by design, I guess that your in your browser or operating system you have dark mode turned on. If darkmode is set to false in this theme, it will still respect the preference of the users machine. When I look at your site, I don't see it in dark mode.

Basically I need to update the docs to make this cleared. But I was also thinking off adding a `darkmode: never` option to always show light mode even if the users preference is dark mode. Do you think this would this be something that would be useful?

**Comment by kurtlocker** [comment]
Oh, interesting, and yes, my OS is configured for dark mode. Thanks for the clarification. It would be cool to have the option to explicitly turn on/off dark mode its not too much trouble.
